version: "3"
services:
  nginx:
    image: 127.0.0.1:5000/nginx
    build: /home/vagrant/containers/nginx/.
    ports: 
      - "8080:8080"
    networks:
      - ourNetwork
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  testresponder:
    image: 127.0.0.1:5000/testresponder
    build: /home/vagrant/containers/testresponder/.
    networks:
      - ourNetwork
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  ourNetwork:
  